### PR TITLE
add logo + resources

### PR DESCRIPTION
**Pull request by robinandeer**
Hi @johandahlberg!

I can't seem to focus enough to do any actual work so this was a nice excursion. I promised a logo and here's my contribution:

logo

I'm not crazy about the color of the wordmark. Red looks better but I'll leave it up to you if you want to make the Super Mario references that obvious :sweat_smile:

### CODE REVIEW

**Comment by johandahlberg** [comment]
Awesome!

**Comment by robinandeer** [comment]
Yipee!!

- [x] bcbio
- [x] NGI_pipeline
- [x] Piper

**Comment by johandahlberg** [comment]
image

**Comment by robinandeer** [comment]
Exactly!

3 down, only 87 million pipelines and counting to go :sweat_smile:

**Pull request merged**
